
module.exports = [

    { id: 'Pos_Fun_0001', input: 'obata suba raathriyak veevaa!!' },
    { id: 'Pos_Fun_0002', input: 'machan  mata vathura oone' },
    { id: 'Pos_Fun_0003', input: 'api passe kathaa karamu.' },
    { id: 'Pos_Fun_0004', input: 'next lecture eka kiiyatadha ?' },
    { id: 'Pos_Fun_0005', input: 'api heta colombo yanavaa, oyath enavada ,api Galle Face yanna hithan inne,iita passe galle yanavaa,aaya enne dhavas thunakin ,udhenma pitath vena nisaa kalin kiyanna puluvannam leesi' },
    { id: 'Pos_Fun_0006', input: 'api heta  set vemudha monava hari kanna' },
    { id: 'Pos_Fun_0007', input: 'mama dhaen vaeda karanava.' },
    { id: 'Pos_Fun_0008', input: 'adoo moko venne?' },
    { id: 'Pos_Fun_0009', input: 'mata ikmanata gedhara yanna oona' },
    { id: 'Pos_Fun_0010', input: 'uba kaeema ekak genaavadha?' },
    { id: 'Pos_Fun_0011', input: 'dhaenmaheta edhdhi magee potha aran enna ,heta ee subject eka thiyanavaa,naeththan  mata liyanna venne paper ekka ,mathak karala potha bag ekata dhaaganna dhaenma' },
    { id: 'Pos_Fun_0012', input: 'api heta apee aluth gedharata yanavaa,ubath enavadha' },
    { id: 'Pos_Fun_0013', input: 'kalin trip yanava kiyala polu tiyanna epaa machan' },
    { id: 'Pos_Fun_0014', input: 'mama heta 7.45 vedhdhi enava class ekata,ee vedhdhi ubath enna' },
    { id: 'Pos_Fun_0015', input: 'suba aluth avurudhdhak veevaa!!' },
    { id: 'Pos_Fun_0016', input: 'adoo vaeda godak thiyanva ,enna vennae ban' },
    { id: 'Pos_Fun_0017', input: 'karuNaakara poddak ida dhenna puluvandha?' },
    { id: 'Pos_Fun_0018', input: 'mata password reset karanna venava,eth OTP eka aave naene thaama' },
    { id: 'Pos_Fun_0019', input: 'hari mama heta udhenma oyata genath dhennam ,baya venna epaa' },
    { id: 'Pos_Fun_0020', input: 'mage bara  80kg idhan 70kg vata adu kara gaththaa' },
    { id: 'Pos_Fun_0021', input: 'adha apita zoom class ekak thiyenne' },
    { id: 'Pos_Fun_0022', input: 'ee  URL eken giyaata passe ,oyaata form ekak fill karanna eyi,eeke NIC  number ekayi  password ekayi  gahanna' },
    { id: 'Pos_Fun_0023', input: 'iilaga exam eka  2025-04-06   patan  gannava kiyala kivvaa' },
    { id: 'Pos_Fun_0024', input: 'anee mata nindha         yanavaa ' },
    // negative test cases
    { id: 'Neg_Fun_0001', input: 'apita rae 12 venna kalin enna Github ekata upload karanna kiyala kivve' },
    { id: 'Neg_Fun_0002', input: 'apita waahana geenna dhenne naee' },
    { id: 'Neg_Fun_0003', input: 'australia kiyanne godak hodha ratak' },
    { id: 'Neg_Fun_0004', input: 'man heta yanawa colombo' },
    { id: 'Neg_Fun_0005', input: 'magee rata Sri Lankawa' },
    { id: 'Neg_Fun_0006', input: 'mata pihinanna puluvan' },
    { id: 'Neg_Fun_0007', input: 'api ethkota aluth  Sony PlayStation 5 ekak gamu' },
    { id: 'Neg_Fun_0008', input: 'apita facebook ekee aluthin reel hadhanna puluvan option ekak thiyanava' },
    { id: 'Neg_Fun_0009', input: 'apee future eka Digitalize velaa ivarayi' },
    { id: 'Neg_Fun_0010', input: 'heta  Stoichiometry lesson eka karanavaa kivve' },

];